name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:

    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v4

      - name: Select latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install package
        working-directory: python
        run: pip install -e .

      - name: Verify import
        run: |
          python -c "from macstt import STT; print(STT)"